# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: chriskyfung/amp-affiliately-jekyll-theme
name: "Bandar Togel"
title: "Daftar 10 Situs Bandar Judi Togel Online Resmi Terpercaya 2023"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Daftar agen situs bandar judi online resmi terbaik dan terpercaya 2023 di indonesia dengan 10 situs bandar pasaran terlengkap deposit via dana, linkaja, ovo, gopay, dan dana.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kiatotosun.gamecreation.org" # the base hostname & protocol for your site, e.g. http://example.com
favicon: 'https://kiatoto8.com/assets/img/aww/favicon.png'
logo: 'https://agenkiatoto.com/logokia.png'
timezone: 'Asia/Bangkok'
twitter_username: jekyllrb
github_username:  jekyll

target_blank: false
anchor_link: true

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"

# Build settings
#theme: minima

# Copyright Start Year
copyright: 
  prefix: 
  ownership: Bandar Togel
  link: /

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
